services:
  postgres:
    image: 'postgres:17.7'
    environment:
      - 'POSTGRES_DB=certmanagement'
      - 'POSTGRES_PASSWORD=runPQSQLN0w'
      - 'POSTGRES_USER=certmgmt_admin'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  rabbitmq:
    image: 'rabbitmq:management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=runRMQN0w'
      - 'RABBITMQ_DEFAULT_USER=root'
    ports:
      - '5672:5672'
      - '15672:15672'
  minio:
    image: 'minio/minio:latest'
    command: server /data --console-address ":9001"
    environment:
      - 'MINIO_ROOT_USER=root'
      - 'MINIO_ROOT_PASSWORD=runMin.ioN0w'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio-data:/data
volumes:
  postgres-data:
    driver: local
  minio-data:
    driver: local
